name: Backend Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o server digitalpaper/backend

      - name: Run tests
        run: go test digitalpaper/backend/... -v -coverprofile=backend_coverage.out -coverpkg=./backend/...

      - uses: codecov/codecov-action@v1
        with:
            fail_ci_if_error: false

      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -v -f ./backend_coverage.out
