name: Frontend Windows

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          version: "18.12.1"

      - name: Install dependencies
        run: cd frontend; npm install

      - name: Build
        run: cd frontend; npm run build