name: Frontend Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          version: '18.12.1'

      - name: NPM - Install dependencies
        run: npm install --prefix frontend

      - name: NPM - Build
        run: npm run build --prefix frontend

      - name: YARN - Install dependencies
        run: yarn --cwd frontend install

      - name: YARN - Build
        run: yarn --cwd frontend run build