name: Ubuntu

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go mod tidy

      - name: Build Project | All
        run: go build -o server digitalpaper/backend
