name: Ubuntu

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-go@v3
              with:
                  go-version: '1.19'

            - name: Install backend dependencies
              run: go mod tidy

            - name: Build backend
              run: go build -o server digitalpaper/backend

            - name: Run backend tests
              run: go test digitalpaper/backend/... -v

            - uses: actions/setup-node@v3
              with:
                version: '18.12.1'

            - name: NPM - Install frontend dependencies
              run: npm install --prefix frontend

            - name: NPM - Build frontend
              run: npm run build --prefix frontend

            - name: YARN - Install frontend dependencies
              run: yarn --cwd frontend install

            - name: YARN - Build frontend
              run: yarn --cwd frontend run build
